/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Alumno
 */
public class ElegirJuego extends javax.swing.JPanel {
    MenuPrincipal framePadre;
    /**
     * Creates new form ModoDeJuego
     */
    public ElegirJuego(MenuPrincipal framePadre) {
        
        setSize(800, 700);
        this.framePadre=framePadre;
        this.framePadre.setTitle("Modo de Juego");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pong1 = new javax.swing.JLabel();
        brillo1 = new javax.swing.JLabel();
        brillo2 = new javax.swing.JLabel();
        brillo3 = new javax.swing.JLabel();
        brillo4 = new javax.swing.JLabel();
        pong = new javax.swing.JLabel();
        arkanoid = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        Pong1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pong1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pong.png"))); // NOI18N

        setBackground(new java.awt.Color(0, 0, 0));

        brillo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N

        brillo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N

        brillo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N

        brillo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N

        pong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pong.png"))); // NOI18N
        pong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pongMouseExited(evt);
            }
        });

        arkanoid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arkanoid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arkanoid.png"))); // NOI18N
        arkanoid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arkanoidMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arkanoidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arkanoidMouseExited(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        back.setText("jLabel1");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brillo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brillo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brillo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arkanoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brillo2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(pong, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arkanoid, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brillo3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brillo4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pongMouseEntered
        pong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pong_hover.png")));
    }//GEN-LAST:event_pongMouseEntered

    private void pongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pongMouseExited
        pong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pong.png")));
    }//GEN-LAST:event_pongMouseExited

    private void arkanoidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arkanoidMouseEntered
        arkanoid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arkanoid_hover.png")));
    }//GEN-LAST:event_arkanoidMouseEntered

    private void arkanoidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arkanoidMouseExited
        arkanoid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arkanoid.png")));
    }//GEN-LAST:event_arkanoidMouseExited

    private void pongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pongMouseClicked
        boolean ver = true;
        
        this.setVisible(!ver);
        
        ModoDeJuego jugar = new ModoDeJuego(framePadre, MenuPrincipal.pong);
        jugar.setVisible(ver);
        framePadre.setContentPane(jugar);
    }//GEN-LAST:event_pongMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha_hover.png")));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png")));
    }//GEN-LAST:event_backMouseExited

    private void arkanoidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arkanoidMouseClicked
        boolean ver = true;
        
        this.setVisible(!ver);
        
        ModoDeJuego jugar = new ModoDeJuego(framePadre, MenuPrincipal.arkanoid);
        jugar.setVisible(ver);
        framePadre.setContentPane(jugar);
    }//GEN-LAST:event_arkanoidMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pong1;
    private javax.swing.JLabel arkanoid;
    private javax.swing.JLabel back;
    private javax.swing.JLabel brillo1;
    private javax.swing.JLabel brillo2;
    private javax.swing.JLabel brillo3;
    private javax.swing.JLabel brillo4;
    private javax.swing.JLabel pong;
    // End of variables declaration//GEN-END:variables
}
