
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saust
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Intento
     */
    public MenuPrincipal() {
        //Insertar fondo con imágenes: la clase que realiza esto está dentro de este mismo archivo JAVA, está más abajo.
        this.setContentPane(new ImagenFondo());        
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        menu.setBackground(new Color(0, 0, 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        brilloB = new javax.swing.JLabel();
        brilloA = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jugar = new javax.swing.JLabel();
        config = new javax.swing.JLabel();
        reglas = new javax.swing.JLabel();

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/config.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(7, 0, 0));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/titulo_sinFondo.png"))); // NOI18N
        titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 89), 1, true));
        menu.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 100));

        brilloB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/brillo_sinFondo.png"))); // NOI18N
        brilloB.setText("jLabel1");
        menu.add(brilloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 90, 76));

        brilloA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/brillo_sinFondo.png"))); // NOI18N
        brilloA.setText("jLabel1");
        menu.add(brilloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 80, 76));

        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario_1.png"))); // NOI18N
        menu.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 800, -1));

        jugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/jugar_sinFondo.png"))); // NOI18N
        jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarMouseClicked(evt);
            }
        });
        menu.add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 800, -1));

        config.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/config_sinFondo.png"))); // NOI18N
        menu.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 800, -1));

        reglas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/reglas_sinFondo.png"))); // NOI18N
        menu.add(reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 800, -1));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseClicked
        boolean ver = true;

        menu.setVisible(!ver);
        Jugar jugar = new Jugar(this);
        jugar.setVisible(ver);
        this.setContentPane(jugar);                       
                                
    }//GEN-LAST:event_jugarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brilloA;
    private javax.swing.JLabel brilloB;
    private javax.swing.JLabel config;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jugar;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel reglas;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
    
    public class ImagenFondo extends JPanel{
        public void paint(Graphics g){
            ImageIcon fondo = new ImageIcon(getClass().getResource("imagenes/ciudadNeon1.png"));
            g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    
    abstract class eventoCerrar implements MouseListener{

        public void actionPerformed(ActionEvent arg0) {
            // TODO Auto-generated method stub
            dispose();
        }
    }
}



