
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saust
 */
public class MenuPrincipal extends javax.swing.JFrame {    

        
    //posibles juegos:
    public static String arkanoid = "arkanoid";
    public static String pong = "pong";
    
    //posibles modos del pong:
    public static String jp = "jp";
    public static String pvp = "pvp";
    public static String pve = "pve";
    
    //posibles modos del arkanoid:
    public static String normal = "normal";
    public static String loco = "loco";
    
    
    //public static String jugar_imagen = "/imagenesSinFondo/jugar_sinFondo.png", jugar_hover_imagen = "/imagenesSinFondo/jugar_hover_sinFondo.png";
    
    /**
     * Creates new form Intento
     */
    public MenuPrincipal() {                        
        //Insertar fondo con imágenes: la clase que realiza esto está dentro de este mismo archivo JAVA, está más abajo.
        this.setContentPane(new ImagenFondo());        
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        menu.setBackground(new Color(0, 0, 0, 120));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        brilloB = new javax.swing.JLabel();
        brilloA = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jugar = new javax.swing.JLabel();
        config = new javax.swing.JLabel();
        reglas = new javax.swing.JLabel();
        jugar_hover = new javax.swing.JLabel();
        config_hover = new javax.swing.JLabel();
        reglas_hover = new javax.swing.JLabel();
        usuario_hover = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/config.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(7, 0, 0));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/logoMarca_sinFondo.png"))); // NOI18N
        titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menu.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 175, 175));

        brilloB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/brillo_sinFondo.png"))); // NOI18N
        brilloB.setText("jLabel1");
        menu.add(brilloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 90, 90));

        brilloA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/brillo_sinFondo.png"))); // NOI18N
        brilloA.setText("jLabel1");
        menu.add(brilloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 90));

        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/usuario_sinFondo.png"))); // NOI18N
        menu.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 800, -1));

        jugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/jugar_sinFondo.png"))); // NOI18N
        jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jugarMouseExited(evt);
            }
        });
        menu.add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 800, -1));

        config.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/config_sinFondo.png"))); // NOI18N
        menu.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 800, -1));

        reglas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/reglas_sinFondo.png"))); // NOI18N
        menu.add(reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 800, -1));

        jugar_hover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugar_hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/jugar_hover_sinFondo.png"))); // NOI18N
        jugar_hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugar_hoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jugar_hoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jugar_hoverMouseExited(evt);
            }
        });
        menu.add(jugar_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 800, 70));

        config_hover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        config_hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/config_hover_sinFondo.png"))); // NOI18N
        menu.add(config_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 800, -1));

        reglas_hover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reglas_hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/reglas_hover_sinFondo.png"))); // NOI18N
        menu.add(reglas_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 800, -1));

        usuario_hover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario_hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/usuario_hover_sinFondo.png"))); // NOI18N
        menu.add(usuario_hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 800, -1));

        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSinFondo/tituloArcadia_sinFondo.png"))); // NOI18N
        titulo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titulo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 189, 89), 1, true));
        menu.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 90));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseClicked
        boolean ver = true;

        menu.setVisible(!ver);
        
        ElegirJuego modo = new ElegirJuego(this);
        modo.setVisible(ver);
        this.setContentPane(modo);
        
        /*Jugar jugar = new Jugar(this);
        jugar.setVisible(ver);
        this.setContentPane(jugar);*/                       
                                
    }//GEN-LAST:event_jugarMouseClicked

    private void jugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseEntered
        
//        jugar.setVisible(false);
//        jugar_hover.setVisible(true);
        //jugar.setBounds((int)getBounds().getMinX()-30, 260, 800, 70);
    }//GEN-LAST:event_jugarMouseEntered

    private void jugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseExited
//#1        
//        jugar.setVisible(true);
//        jugar_hover.setVisible(false);
        

//#2//      
    //


//#3 //jugar.setBounds(300, 260, 800, 70);
        
    }//GEN-LAST:event_jugarMouseExited

    private void jugar_hoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar_hoverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jugar_hoverMouseClicked

    private void jugar_hoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar_hoverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jugar_hoverMouseEntered

    private void jugar_hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar_hoverMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jugar_hoverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
                jugar.setBackground(Color.red);
                jugar_hover.setBackground(Color.red);
                jugar_hover.setVisible(false);
                
                
                config.setBackground(new Color(0,0,0,0));
                config_hover.setBackground(new Color(0,0,0,0));
                config_hover.setVisible(false);
                
                
                reglas.setBackground(new Color(0,0,0,0));
                reglas_hover.setBackground(new Color(0,0,0,0));
                reglas_hover.setVisible(false);
                
                
                usuario.setBackground(new Color(0,0,0,0));
                usuario_hover.setBackground(new Color(0,0,0,0));
                usuario_hover.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brilloA;
    private javax.swing.JLabel brilloB;
    private static javax.swing.JLabel config;
    private static javax.swing.JLabel config_hover;
    private javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jugar;
    private static javax.swing.JLabel jugar_hover;
    private javax.swing.JPanel menu;
    private static javax.swing.JLabel reglas;
    private static javax.swing.JLabel reglas_hover;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private static javax.swing.JLabel usuario;
    private static javax.swing.JLabel usuario_hover;
    // End of variables declaration//GEN-END:variables
    
    public class ImagenFondo extends JPanel{
        
        public void paint(Graphics g){
            ImageIcon fondo = new ImageIcon(getClass().getResource("imagenes/ciudadNeon1.png"));
            g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    
    abstract class eventoCerrar implements MouseListener{

        public void actionPerformed(ActionEvent arg0) {
            // TODO Auto-generated method stub
            dispose();
        }
    }
}



