import clases.Ventana;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import principal.Principal;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author saust
 */
public class ModoDeJuego extends javax.swing.JPanel {    
    MenuPrincipal framePadre;
    static String juego;
    static String modo;
    static String urlImagen [] = new String [10];    
    /**
     * Creates new form jugar
     */
    
    public ModoDeJuego(MenuPrincipal x, String juego) {
        framePadre=x;
        this.juego=juego;
        
        if(juego.equals(MenuPrincipal.pong)){
            urlImagen [1] = "/imagenes/jp.png";
            urlImagen [2] = "/imagenes/pvp.png";
            urlImagen [3] = "/imagenes/pve.png";
        }
        else if(juego.equals(MenuPrincipal.arkanoid)){
            urlImagen [1] = "/imagenes/normal.png";
            urlImagen [2] = "/imagenes/loco.png";
            urlImagen [3] = "/imagenes/loco.png";
        }
        
        initComponents();
        //setBackground(new Color(0, 0, 0, 0));
    }                                                                                                                               

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp = new javax.swing.JLabel();
        pve = new javax.swing.JLabel();
        pvp = new javax.swing.JLabel();
        brillo1 = new javax.swing.JLabel();
        brillo2 = new javax.swing.JLabel();
        brillo3 = new javax.swing.JLabel();
        brillo4 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp.setIcon(new javax.swing.ImageIcon(getClass().getResource(urlImagen[1])));
        jp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMouseClicked(evt);
            }
        });
        add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 220, 700));

        pve.setIcon(new javax.swing.ImageIcon(getClass().getResource(urlImagen[3])));
        add(pve, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 160, 700));

        pvp.setIcon(new javax.swing.ImageIcon(getClass().getResource(urlImagen[2])));
        pvp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pvpMouseClicked(evt);
            }
        });
        add(pvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 180, 700));

        brillo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N
        add(brillo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 90, 90, 110));

        brillo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N
        add(brillo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, 110));

        brillo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N
        add(brillo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 90, 110));

        brillo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brillo.png"))); // NOI18N
        add(brillo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 500, 90, 110));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        back.setText("jLabel1");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMouseClicked
        
    //#Borra el Frame anterior
        framePadre.dispose();
    
        if(juego.equals(MenuPrincipal.arkanoid)){
            modo=MenuPrincipal.normal;                  
        }
        
        if(juego.equals(MenuPrincipal.pong)){
            modo=MenuPrincipal.jp;
        }
        
        
    //#Dos maneras exactamente iguales de ejecutar la clase Principal:
    //(1)
        Principal principal = new Principal(juego, modo);        
    //(2)
        /*String[] args = null;
        Principal.main(args);*/
    }//GEN-LAST:event_jpMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha_hover.png")));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png")));
    }//GEN-LAST:event_backMouseExited

    private void pvpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvpMouseClicked
                
    //#Borra el Frame anterior
        framePadre.dispose();
    
        
    //#Dos maneras exactamente iguales de ejecutar la clase Principal:
    //(1)
        Principal principal = new Principal("pong", "pvp");        
    //(2)
        /*String[] args = null;
        Principal.main(args);*/
    }//GEN-LAST:event_pvpMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel brillo1;
    private javax.swing.JLabel brillo2;
    private javax.swing.JLabel brillo3;
    private javax.swing.JLabel brillo4;
    private javax.swing.JLabel jp;
    private javax.swing.JLabel pve;
    private javax.swing.JLabel pvp;
    // End of variables declaration//GEN-END:variables
}
